// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: proto/substrate.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventBridgeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                        // Version
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                  // ID
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                          // Source
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`                        // Account
	Time          string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`                              // Time
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`                          // Region
	Resources     []string               `protobuf:"bytes,7,rep,name=resources,proto3" json:"resources,omitempty"`                    // Resources
	DetailType    string                 `protobuf:"bytes,8,opt,name=detailType,json=detail-type,proto3" json:"detailType,omitempty"` // Detail type
	Detail        *Transport             `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`                          // Detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBridgeEvent) Reset() {
	*x = EventBridgeEvent{}
	mi := &file_proto_substrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBridgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBridgeEvent) ProtoMessage() {}

func (x *EventBridgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_substrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBridgeEvent.ProtoReflect.Descriptor instead.
func (*EventBridgeEvent) Descriptor() ([]byte, []int) {
	return file_proto_substrate_proto_rawDescGZIP(), []int{0}
}

func (x *EventBridgeEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EventBridgeEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventBridgeEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventBridgeEvent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EventBridgeEvent) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *EventBridgeEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EventBridgeEvent) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *EventBridgeEvent) GetDetailType() string {
	if x != nil {
		return x.DetailType
	}
	return ""
}

func (x *EventBridgeEvent) GetDetail() *Transport {
	if x != nil {
		return x.Detail
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Substrate     string                 `protobuf:"bytes,1,opt,name=substrate,proto3" json:"substrate,omitempty"`     // Substrate name
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`       // Substrate feature flags
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`           // Substrate source
	Destination   []string               `protobuf:"bytes,4,rep,name=destination,proto3" json:"destination,omitempty"` // Substrate destination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_substrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_substrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_substrate_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetSubstrate() string {
	if x != nil {
		return x.Substrate
	}
	return ""
}

func (x *Header) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Header) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Header) GetDestination() []string {
	if x != nil {
		return x.Destination
	}
	return nil
}

type Transport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // Header
	Body          *anypb.Any             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`     // Body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_proto_substrate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_substrate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_proto_substrate_proto_rawDescGZIP(), []int{2}
}

func (x *Transport) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Transport) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_substrate_proto protoreflect.FileDescriptor

var file_proto_substrate_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x02,
	0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0a, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x75, 0x62, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x7c, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_substrate_proto_rawDescOnce sync.Once
	file_proto_substrate_proto_rawDescData []byte
)

func file_proto_substrate_proto_rawDescGZIP() []byte {
	file_proto_substrate_proto_rawDescOnce.Do(func() {
		file_proto_substrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_substrate_proto_rawDesc), len(file_proto_substrate_proto_rawDesc)))
	})
	return file_proto_substrate_proto_rawDescData
}

var file_proto_substrate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_substrate_proto_goTypes = []any{
	(*EventBridgeEvent)(nil), // 0: substrate.EventBridgeEvent
	(*Header)(nil),           // 1: substrate.Header
	(*Transport)(nil),        // 2: substrate.Transport
	(*anypb.Any)(nil),        // 3: google.protobuf.Any
}
var file_proto_substrate_proto_depIdxs = []int32{
	2, // 0: substrate.EventBridgeEvent.detail:type_name -> substrate.Transport
	1, // 1: substrate.Transport.header:type_name -> substrate.Header
	3, // 2: substrate.Transport.body:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_substrate_proto_init() }
func file_proto_substrate_proto_init() {
	if File_proto_substrate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_substrate_proto_rawDesc), len(file_proto_substrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_substrate_proto_goTypes,
		DependencyIndexes: file_proto_substrate_proto_depIdxs,
		MessageInfos:      file_proto_substrate_proto_msgTypes,
	}.Build()
	File_proto_substrate_proto = out.File
	file_proto_substrate_proto_goTypes = nil
	file_proto_substrate_proto_depIdxs = nil
}
